#!/usr/bin/env bash
set -euo pipefail

repo_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
snapshot_dir="$repo_dir/snapshots/current"

mkdir -p "$snapshot_dir"

write_header() {
  local file="$1"
  {
    echo "# Generated by ./sync.sh snapshot"
    echo "# Safe inventory only. No auth tokens, SSH keys, casks, or app installs."
    echo
  } > "$file"
}

command_exists() {
  command -v "$1" >/dev/null 2>&1
}

write_command_output() {
  local file="$1"
  shift

  write_header "$file"

  if "$@" >> "$file" 2>/dev/null; then
    return
  fi

  echo "# unavailable" >> "$file"
}

write_sorted_command_output() {
  local file="$1"
  shift

  write_header "$file"

  if "$@" 2>/dev/null | sort -u >> "$file"; then
    return
  fi

  echo "# unavailable" >> "$file"
}

safe_git_config() {
  local keys=(
    user.name
    user.email
    init.defaultBranch
    pull.rebase
    push.autoSetupRemote
    core.editor
    core.pager
    interactive.diffFilter
    delta.navigate
    merge.conflictstyle
    rerere.enabled
    rebase.autoStash
  )

  local key value
  for key in "${keys[@]}"; do
    if value="$(git config --global --get "$key" 2>/dev/null)"; then
      printf '%s=%s\n' "$key" "$value"
    fi
  done
}

npm_globals() {
  npm ls -g --depth=0 --parseable 2>/dev/null \
    | tail -n +2 \
    | while IFS= read -r package_path; do basename "$package_path"; done
}

pnpm_globals() {
  pnpm list -g --depth=0 --parseable 2>/dev/null \
    | tail -n +2 \
    | while IFS= read -r package_path; do basename "$package_path"; done
}

yarn_globals() {
  yarn global list --depth=0 2>/dev/null \
    | sed -n 's/^info "\([^"]*\)@.*$/\1/p'
}

write_header "$snapshot_dir/metadata.txt"
{
  printf 'generated_at_utc=%s\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  printf 'os=%s\n' "$(uname -s)"
  printf 'arch=%s\n' "$(uname -m)"
  if command_exists sw_vers; then
    sw_vers | sed 's/:[[:space:]]*/=/'
  fi
} >> "$snapshot_dir/metadata.txt"

if command_exists brew; then
  write_sorted_command_output "$snapshot_dir/brew-formulae.txt" brew leaves
  write_sorted_command_output "$snapshot_dir/brew-taps.txt" brew tap
else
  write_header "$snapshot_dir/brew-formulae.txt"
  echo "# brew unavailable" >> "$snapshot_dir/brew-formulae.txt"
  write_header "$snapshot_dir/brew-taps.txt"
  echo "# brew unavailable" >> "$snapshot_dir/brew-taps.txt"
fi

if command_exists npm; then
  write_sorted_command_output "$snapshot_dir/npm-global.txt" npm_globals
else
  write_header "$snapshot_dir/npm-global.txt"
  echo "# npm unavailable" >> "$snapshot_dir/npm-global.txt"
fi

if command_exists pnpm; then
  write_sorted_command_output "$snapshot_dir/pnpm-global.txt" pnpm_globals
else
  write_header "$snapshot_dir/pnpm-global.txt"
  echo "# pnpm unavailable" >> "$snapshot_dir/pnpm-global.txt"
fi

if command_exists yarn; then
  write_sorted_command_output "$snapshot_dir/yarn-global.txt" yarn_globals
else
  write_header "$snapshot_dir/yarn-global.txt"
  echo "# yarn unavailable" >> "$snapshot_dir/yarn-global.txt"
fi

if command_exists gh; then
  write_sorted_command_output "$snapshot_dir/gh-extensions.txt" gh extension list
else
  write_header "$snapshot_dir/gh-extensions.txt"
  echo "# gh unavailable" >> "$snapshot_dir/gh-extensions.txt"
fi

write_sorted_command_output "$snapshot_dir/git-config.safe.txt" safe_git_config

write_header "$snapshot_dir/cli-versions.txt"
{
  for binary in git gh node npm pnpm yarn python3 uv uvx rg fd jq; do
    if command_exists "$binary"; then
      printf '## %s\n' "$binary"
      "$binary" --version 2>/dev/null | head -n 1 || true
      echo
    fi
  done
} >> "$snapshot_dir/cli-versions.txt"

"$repo_dir/scripts/secret-guard.sh" "$snapshot_dir"

echo "Snapshot written to $snapshot_dir"
